### ISSUE TITLE
Can you provide train_lss.pt?

### ISSUE THREAD

**Issue by crankler** [ctu-vras/monoforce#1]
Hi, thanks for your interesting work here.
I think considering the terrain proterity into the map is a useful work, which I also foucsed on.
Can you provide a few terrain_lss.pt file, so I can try.
Hope you can reply, thank you again.

**Comment by rlnav** [comment]
Hi. Thanks for your interest. We provide the link to the pretrained model weights. Please, check the updated [documentation](https://github.com/ctu-vras/monoforce?tab=readme-ov-file#weights). However, note that the work is under development. And we might release a newer version for the terrain encoder in the nearest time.

Ruslan

**Comment by crankler** [comment]
Thank you for your share here, I have tried this code for our work.
However, my pkg located in indoor enviroments, so the results are not well.
I will try to recity code to adapt our perception.

**Comment by rlnav** [comment]
Feel free to train the model on your data. Have a look at the [training script](https://github.com/ctu-vras/monoforce/blob/b476a3b3e59b4bfb22125ec0f9073aaa83b73f48/scripts/train) and [data format](https://github.com/ctu-vras/monoforce/blob/master/docs/DATA.md) for more information.
